feat: отрисовал главный экран с 3 компонентами
Imanalinov/react-burger pull request #1
Opened 2024-01-23 04:56 UTC by Imanalinov

1. AppHeader
2. BurgerConstructor
3. BurgerIngredients

2024-01-23 06:03 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/Mh_xoxhfMQqEGg> - Активной должна быть только первая ссылка;

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- По чек-листу, стили портированы как модули. А если есть общие стили, они портированы в глобальную область видимости.

- Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2024-01-23 06:03 UTC, ArslanMustafin commented on src/App.tsx
> +      <div style={{display: 'flex', gap: '40px'}}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      <div className={`mt-5`} style={{ display: 'flex' }}>
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +}
**Надо исправить:**

Нужно вынести в отдельный компонент и папку. А также описать `prop-types`.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  ingredientList: PropTypes.array
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.array.
А также необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Во многих компонентах будет дублироваться описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингредиента, а не дублировать

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  }
**Надо исправить:**

Функция немного избыточна.

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

А остальное можно перенести в `jsx`. Старайтесь избегать создания лишних функций для вывода JSX, так как это может усложнить код и сделать его менее поддерживаемым

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +};
**Надо исправить:**

Нужно вынести в отдельный компонент и папку. А также описать `prop-types`.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +};
**Можно лучше:**

Эту функцию лучше вынести в утилиты. И кажется, тут лучше подойдёт конструкция `switch-case`

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  });
**Надо исправить:**

Не стоит добавлять в `useState` вложенные структуры данных, если в этом нет необходимости.

В данном случае, лучше всего тут будет добавить просто массив ингредиентов, не разделяя их по типу. А также перенести это всё выше, в компонент `app`. Т.к. эти данные также будут нужны в компоненте `burger-constructor`. 

```js
  const [data, setData] = useState({
    loading: false,
    error: false,
    ingredients: DATA;
  });
  
  // ... 
  
  <BurgerIngredients ingredients={data.ingredients} />
  <BurgerConstructor constructorIngredients={data.ingredients} />
```

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, []);
**Надо исправить:**

В данном случае `useEffect` не нужен. В следующих итерациях вы начнёте работать с сервером, и уже там будете использовать `useEffect`.

```js
const BurgerIngredients = (data) => {
  const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
  const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
  const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);
  
  // ....
}
```

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  };
**Надо исправить:**

Данный функционал сейчас не нужен, поэтому рекомендую его убрать. Этот функционал вы будете делать когда изучите редакс.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  };
**Надо исправить:**

Используйте прямое внедрение JSX в компоненты, чтобы сделать код более читаемым и легким для понимания. Избегайте создания лишних функций для вывода JSX, так как это может усложнить код и сделать его менее поддерживаемым.

Если же вы хотите отделить кусок кода, то нужно создавать отдельный компонент. В данном случае у каждой категории ингредиентов дублируется верстка, лучше вынести в отдельный компонент ingredients-category и переиспользовать его.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/index.tsx
> +  // <React.StrictMode>
**Можно лучше:**

Рекомендую включить Strict Mode. Strict Mode делает более строгую проверку некоторых побочных эффектов, таких как изменения состояния внутри рендера. Это может помочь избежать неявных и нежелательных изменений состояния, которые могут привести к багам.

2024-01-23 06:03 UTC, ArslanMustafin commented on src/utils/array-prototype.js
> +
**Надо исправить:**

не совсем понимаю, зачем это нужно.

если вам нужно получить последний элемент массива, то в `js` есть метод `at`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

```js
const array = [5, 12, 8, 130, 44];

const index = -1;

console.log(`An index of ${index} returns ${array.at(index)}`);
// Expected output: "An index of -1 returns 44"

```

2024-01-23 10:00 UTC, Imanalinov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, []);
В этом случае немного не понял, получает можно убрать `setState` и создать как обычную константу?

2024-01-24 06:15 UTC, Imanalinov commented
Здравствуйте! 

Я исправил ваши комментарии. 

Спасибо!

2024-01-26 16:32 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличая работа.

### **Вы молодец! Приступайте к выполнению следующего этапа, не пугайтесь, работа не принята, чтобы была возможность отправить на проверку следующий этап.**

- Все замечания были исправлены;

2024-01-26 16:32 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  const filteredIngredientList = useMemo(() => constructorIngredients.filter(
**Можно лучше:**

Лучше изначально разделить булку и ингредиенты (По заданию, булка всегда будет одна и та же, поэтому лучше не делить их на две отдельные):

```js
const { bun, ingredients } = useMemo(() => {
  return {
    bun: data.find(item => item.type === 'bun'),
    ingredients: data.filter(item => item.type !== 'bun'),
  };
}, [data]);
```

2024-01-26 16:32 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +            text={constructorIngredients[0].name}
**Надо исправить:**

По макету у булок должна быть приписка `(верх)` и `(низ)`.

2024-01-30 04:34 UTC, merged